# Generated by Django 5.0.3 on 2024-03-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Cuisine', models.CharField(max_length=50)),
                ('meals_type', models.CharField(max_length=20)),
                ('Ingrediants', models.TextField()),
                ('Instruction', models.TextField()),
                ('Created_at', models.DateTimeField()),
                ('Upto_date', models.DateTimeField()),
            ],
        ),
    ]
