# Generated by Django 5.0.3 on 2024-03-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipieapp', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Ingrediants',
            new_name='Ingredients',
        ),
    ]
